import = [
    "~/.config/alacritty/themes/cyber_punk_neon.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 8

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.offset]
x = 0
y = 1

[scrolling]
history = 5000

[shell]
program = "/usr/bin/zsh"

[window]
decorations = "none"
dynamic_padding = false
opacity = 0.95
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6
